### ISSUE TITLE
Installing under WSL

### ISSUE THREAD

**Issue by ancucchi** [Gadzhovski/TRACE-Forensic-Toolkit#2]
I am trying to install TRACE under WSL where is running:

- OS: Ubuntu 22.04.4 LTS on Windows 10 x86_64
- Kernel: 5.15.153.1-microsoft-standard-WSL2
- Python 3.10.12
-  pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

As requested i execute:
`pip install -r requirements.txt`

but during installation of requested this message appear:
```
ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14
```
Then I download 
`python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl`
and tried to install it manually with
`pip install python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl`
but during installation of requested this message appear:
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl is not a supported wheel on this platform.
```
Where I wrong?

PS
I tried to install `python_magic_bin` with
`pip install git+https://github.com/julian-r/python-magic.git`
Is it a good idea?

**Comment by Gadzhovski** [comment]
**try this:**

**Install libmagic on your Ubuntu WSL:**
```
sudo apt-get update
sudo apt-get install libmagic1
```

**Manually install python-magic not "python_magic_bin":**
`pip install python-magic`

**Comment by Gadzhovski** [comment]
Hi  @ancucchi ,

I've made an update that should resolve the problem you encountered when installing our software on WSL. Please pull the latest changes from the main branch of our repository and follow the updated installation instructions in the README. 

Could you please try the new installation process and let me know if it resolves your issue? Your feedback will be very helpful.

Thank you!
