### ISSUE TITLE
Raw images fail to mount macos

### ISSUE THREAD

**Issue by Rebootkid** [Gadzhovski/TRACE-Forensic-Toolkit#3]
Attempting to mount dd image that is known clean receive this error on a fresh install:

"Failed to mount the image. Error: [Errno 13] Permission denied: 'tools/Arsenal-Image-Mounter-v3.10.257/aim_cli.exe"

<img width="252" alt="image" src="https://github.com/user-attachments/assets/9a4b7407-d7c8-4c48-9bab-7f6f9ab8977c">

Manually setting execute rights with a chmod +x yields this error:
Failed to mount the image: Error: [Errno8] Exec format error: 'tools/Arsenal-Image-Mounter-v3.10.257/aim_cli.exe'

<img width="251" alt="image" src="https://github.com/user-attachments/assets/9b08a471-4ba4-4bab-b030-b8db6b04bdab">

**Comment by Gadzhovski** [comment]
As written in the description the mounting is only supported for Windows as I used Arsenal Image Mounter(executable) 
![image](https://github.com/user-attachments/assets/0167ec28-f923-4ce7-a564-253f3de6672a)

**Comment by Gadzhovski** [comment]
I will try to work on implementing this feature on macOS and Linux these days!

**Comment by Rebootkid** [comment]
Ahh. Apologies. I'd thought that was more about the format of the source file system. i.e. you can only mount a windows file system.

If it's a mounting question, the OS should have items built in natively that could be invoked. diskutil in mac, mount in linux, if it's supposed to be mounted directly.

**Comment by Gadzhovski** [comment]
Yes, I think I will be able to push the update tomorrow,  will use "hdiutil" and "ewfmount" for mounting disk images on macOS. :)
